class ServiceResult<T> {
  final ServiceStatusCode statusCode;
  final String? message;
  final T content;
  ServiceResult({required this.statusCode, this.message, required this.content});
}

enum ServiceStatusCode {
  Continue,
  SwitchingProtocols,
  Processing,
  EarlyHints,
  OK,
  Created,
  Accepted,
  NonAuthoritativeInformation,
  NoContent,
  ResetContent,
  PartialContent,
  MultiStatus,
  AlreadyReported,
  IMUsed,
  MultipleChoices,
  Ambiguous,
  MovedPermanently,
  Moved,
  Found,
  Redirect,
  SeeOther,
  RedirectMethod,
  NotModified,
  UseProxy,
  Unused,
  TemporaryRedirect,
  RedirectKeepVerb,
  PermanentRedirect,
  BadRequest,
  Unauthorized,
  PaymentRequired,
  Forbidden,
  NotFound,
  MethodNotAllowed,
  NotAcceptable,
  ProxyAuthenticationRequired,
  RequestTimeout,
  Conflict,
  Gone,
  LengthRequired,
  PreconditionFailed,
  RequestEntityTooLarge,
  RequestUriTooLong,
  UnsupportedMediaType,
  RequestedRangeNotSatisfiable,
  ExpectationFailed,
  MisdirectedRequest,
  UnprocessableEntity,
  Locked,
  FailedDependency,
  UpgradeRequired,
  PreconditionRequired,
  TooManyRequests,
  RequestHeaderFieldsTooLarge,
  UnavailableForLegalReasons,
  InternalServerError,
  NotImplemented,
  BadGateway,
  ServiceUnavailable,
  GatewayTimeout,
  HttpVersionNotSupported,
  VariantAlsoNegotiates,
  InsufficientStorage,
  LoopDetected,
  NotExtended,
  NetworkAuthenticationRequired,
  SystemException,
  NetworkFailure
}

final StatusCode = {
  ServiceStatusCode.Continue: 100,
  ServiceStatusCode.SwitchingProtocols: 101,
  ServiceStatusCode.Processing: 102,
  ServiceStatusCode.EarlyHints: 103,
  ServiceStatusCode.OK: 200,
  ServiceStatusCode.Created: 201,
  ServiceStatusCode.Accepted: 202,
  ServiceStatusCode.NonAuthoritativeInformation: 203,
  ServiceStatusCode.NoContent: 204,
  ServiceStatusCode.ResetContent: 205,
  ServiceStatusCode.PartialContent: 206,
  ServiceStatusCode.MultiStatus: 207,
  ServiceStatusCode.AlreadyReported: 208,
  ServiceStatusCode.IMUsed: 226,
  ServiceStatusCode.MultipleChoices: 300,
  ServiceStatusCode.Ambiguous: 300,
  ServiceStatusCode.MovedPermanently: 301,
  ServiceStatusCode.Moved: 301,
  ServiceStatusCode.Found: 302,
  ServiceStatusCode.Redirect: 302,
  ServiceStatusCode.SeeOther: 303,
  ServiceStatusCode.RedirectMethod: 303,
  ServiceStatusCode.NotModified: 304,
  ServiceStatusCode.UseProxy: 305,
  ServiceStatusCode.Unused: 306,
  ServiceStatusCode.TemporaryRedirect: 307,
  ServiceStatusCode.RedirectKeepVerb: 307,
  ServiceStatusCode.PermanentRedirect: 308,
  ServiceStatusCode.BadRequest: 400,
  ServiceStatusCode.Unauthorized: 401,
  ServiceStatusCode.PaymentRequired: 402,
  ServiceStatusCode.Forbidden: 403,
  ServiceStatusCode.NotFound: 404,
  ServiceStatusCode.MethodNotAllowed: 405,
  ServiceStatusCode.NotAcceptable: 406,
  ServiceStatusCode.ProxyAuthenticationRequired: 407,
  ServiceStatusCode.RequestTimeout: 408,
  ServiceStatusCode.Conflict: 409,
  ServiceStatusCode.Gone: 410,
  ServiceStatusCode.LengthRequired: 411,
  ServiceStatusCode.PreconditionFailed: 412,
  ServiceStatusCode.RequestEntityTooLarge: 413,
  ServiceStatusCode.RequestUriTooLong: 414,
  ServiceStatusCode.UnsupportedMediaType: 415,
  ServiceStatusCode.RequestedRangeNotSatisfiable: 416,
  ServiceStatusCode.ExpectationFailed: 417,
  ServiceStatusCode.MisdirectedRequest: 421,
  ServiceStatusCode.UnprocessableEntity: 422,
  ServiceStatusCode.Locked: 423,
  ServiceStatusCode.FailedDependency: 424,
  ServiceStatusCode.UpgradeRequired: 426,
  ServiceStatusCode.PreconditionRequired: 428,
  ServiceStatusCode.TooManyRequests: 429,
  ServiceStatusCode.RequestHeaderFieldsTooLarge: 431,
  ServiceStatusCode.UnavailableForLegalReasons: 451,
  ServiceStatusCode.InternalServerError: 500,
  ServiceStatusCode.NotImplemented: 501,
  ServiceStatusCode.BadGateway: 502,
  ServiceStatusCode.ServiceUnavailable: 503,
  ServiceStatusCode.GatewayTimeout: 504,
  ServiceStatusCode.HttpVersionNotSupported: 505,
  ServiceStatusCode.VariantAlsoNegotiates: 506,
  ServiceStatusCode.InsufficientStorage: 507,
  ServiceStatusCode.LoopDetected: 508,
  ServiceStatusCode.NotExtended: 510,
  ServiceStatusCode.NetworkAuthenticationRequired: 0x1FF,
  ServiceStatusCode.NetworkFailure: 500,
  ServiceStatusCode.SystemException: 999
};
